"""
Book Detection — YOLO11n
========================
Camera  : SO-100 robot camera (UVC 32x32)
          Falls back to laptop webcam automatically if robot cam not found
Model   : yolo11n.pt
Arm     : Placeholder — detection works standalone, arm bridge added later

Install
-------
pip install numpy opencv-python ultralytics

Usage
-----
python main.py               # auto-detects robot camera, else falls back to webcam
python main.py --webcam      # force laptop webcam (for testing YOLO only)
python main.py --camera 2    # manually pick a camera index
"""

import sys
import argparse
import time
import os
import json
import numpy as np
import cv2
from ultralytics import YOLO
import cv2.aruco


# ══════════════════════════════════════════════════════════════════════════════
#  CONFIGURATION
# ══════════════════════════════════════════════════════════════════════════════

MODEL_PATH        = "yolo11n.pt"
CONFIDENCE_THRESH = 0.40
DETECT_PEOPLE     = False         # Set to True to also detect people

# SO-100 robot camera resolution (standard USB camera)
ROBOT_CAM_WIDTH   = 640
ROBOT_CAM_HEIGHT  = 480

# Software zoom — crop factor (1.0 = no zoom, 2.0 = 2x zoom, etc.)
# Change at runtime with '+' / '-' keys, or set the default here
ZOOM_DEFAULT      = 1.0
ZOOM_MIN          = 1.0
ZOOM_MAX          = 5.0
ZOOM_STEP         = 0.25

# Depth estimation (pinhole approximation)
KNOWN_BOOK_WIDTH_M = 0.21  # real-world book width in metres
FOCAL_LENGTH_PX    = 600.0 # fallback — overridden by camera_calibration.json if present

# Calibration files (generated by calibrate_camera.py / calibrate_workspace.py)
# Paths are resolved relative to this script's directory so the script works
# regardless of which directory it is launched from.
_SCRIPT_DIR          = os.path.dirname(os.path.abspath(__file__))
CAMERA_CALIB_FILE    = os.path.join(_SCRIPT_DIR, "camera_calibration.json")
WORKSPACE_CALIB_FILE = os.path.join(_SCRIPT_DIR, "workspace_calibration.json")


# ══════════════════════════════════════════════════════════════════════════════
#  CALIBRATION LOADERS
# ══════════════════════════════════════════════════════════════════════════════

def load_camera_calibration():
    """Load camera intrinsics. Returns (cam_matrix, dist_coeffs, fx) or Nones."""
    if not os.path.exists(CAMERA_CALIB_FILE):
        print(f"[CALIB] {CAMERA_CALIB_FILE} not found — using defaults.")
        return None, None, FOCAL_LENGTH_PX
    with open(CAMERA_CALIB_FILE) as f:
        data = json.load(f)
    cam_matrix  = np.array(data["camera_matrix"], dtype=np.float64)
    dist_coeffs = np.array(data["dist_coeffs"], dtype=np.float64)
    fx = cam_matrix[0, 0]
    print(f"[CALIB] Camera intrinsics loaded — fx={fx:.1f} px")
    return cam_matrix, dist_coeffs, fx


def load_workspace_calibration():
    """Load workspace polygon (pixel corners). Returns np array or None."""
    if not os.path.exists(WORKSPACE_CALIB_FILE):
        print(f"[CALIB] {WORKSPACE_CALIB_FILE} not found — workspace filter DISABLED.")
        return None, None
    with open(WORKSPACE_CALIB_FILE) as f:
        data = json.load(f)
    pixel_corners = np.array(data["pixel_corners"], dtype=np.int32)
    homography    = np.array(data["homography"],    dtype=np.float64)
    ws = data["workspace_m"]
    print(f"[CALIB] Workspace loaded — {ws[0]*100:.0f}cm × {ws[1]*100:.0f}cm  "
          f"({len(pixel_corners)} corner polygon)")
    return pixel_corners, homography


# ══════════════════════════════════════════════════════════════════════════════
#  CAMERA SETUP
#  Tries to find the robot camera first, falls back to webcam
# ══════════════════════════════════════════════════════════════════════════════

def find_robot_camera():
    """
    Scans camera indices 0-5 and returns the first one that can be
    opened. Prefers indices > 0 (external USB cam) over the built-in
    webcam at index 0.  Returns None if nothing is found.
    """
    print("[CAM] Scanning for robot camera ...")
    for idx in range(1, 6):          # try external cameras first
        cap = cv2.VideoCapture(idx)
        if not cap.isOpened():
            cap.release()
            continue
        cap.set(cv2.CAP_PROP_FRAME_WIDTH,  ROBOT_CAM_WIDTH)
        cap.set(cv2.CAP_PROP_FRAME_HEIGHT, ROBOT_CAM_HEIGHT)
        w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        cap.release()
        print(f"[CAM] Robot camera found at index {idx} ({w}x{h})")
        return idx
    print("[CAM] Robot camera not found.")
    return None


def open_camera(index, robot_mode):
    cap = cv2.VideoCapture(index)
    if not cap.isOpened():
        raise RuntimeError(f"Cannot open camera at index {index}.")
    if robot_mode:
        cap.set(cv2.CAP_PROP_FRAME_WIDTH,  ROBOT_CAM_WIDTH)
        cap.set(cv2.CAP_PROP_FRAME_HEIGHT, ROBOT_CAM_HEIGHT)
        w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        print(f"[CAM] Robot camera opened — {w}x{h}")
    else:
        w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        print(f"[CAM] Webcam opened — {w}x{h}  (YOLO test mode)")
    return cap


# ══════════════════════════════════════════════════════════════════════════════
#  VISION HELPERS
# ══════════════════════════════════════════════════════════════════════════════

def crop_zoom(frame, zoom):
    """Return a centre-cropped and re-scaled version of *frame*."""
    if zoom <= 1.0:
        return frame
    h, w = frame.shape[:2]
    crop_w = int(w / zoom)
    crop_h = int(h / zoom)
    x0 = (w - crop_w) // 2
    y0 = (h - crop_h) // 2
    cropped = frame[y0:y0 + crop_h, x0:x0 + crop_w]
    return cv2.resize(cropped, (w, h), interpolation=cv2.INTER_LINEAR)


def estimate_depth_m(bbox_width_px, focal_length=None):
    if bbox_width_px < 1:
        return float("inf")
    fl = focal_length if focal_length is not None else FOCAL_LENGTH_PX
    return (KNOWN_BOOK_WIDTH_M * fl) / bbox_width_px


def bbox_centre_normalised(x1, y1, x2, y2, fw, fh):
    """Returns (cx, cy) in [-1, 1] with (0, 0) at frame centre."""
    cx = ((x1 + x2) / 2) / fw * 2 - 1
    cy = ((y1 + y2) / 2) / fh * 2 - 1
    return cx, cy


# ══════════════════════════════════════════════════════════════════════════════
#  ARM BRIDGE PLACEHOLDER
#  ─────────────────────────────────────────────────────────────────────────────
#  This function is called every frame a book is detected.
#  Replace the body with your lerobot / dynamixel-sdk arm commands.
#
#  Args passed in:
#    cx_norm  — horizontal offset from frame centre, -1 (left)  to +1 (right)
#    cy_norm  — vertical offset from frame centre,   -1 (top)   to +1 (bottom)
#    depth_m  — estimated distance to book in metres
# ══════════════════════════════════════════════════════════════════════════════

def send_to_arm(x, y, z):
    """
    Send target coordinates to robot arm.
    
    Args:
      x  — horizontal position (normalized -1 to +1, or pixel coordinate)
      y  — vertical position (normalized -1 to +1, or pixel coordinate)
      z  — depth in metres from camera
    """
    # ── TODO: plug arm control in here ───────────────────────────────────────
    #
    # Example (lerobot):
    #   robot.send_action({
    #       "joint_pan":   x * 0.5,
    #       "joint_tilt":  y * 0.3,
    #       "joint_reach": max(0.0, z - 0.20),
    #   })
    #
    # Example (dynamixel-sdk):
    #   pan_pos = centre + int(x * scale)
    #   packet_handler.write4ByteTxRx(port, SERVO_PAN, ADDR_GOAL_POS, pan_pos)
    #
    pass


# ══════════════════════════════════════════════════════════════════════════════
#  MAIN LOOP
# ══════════════════════════════════════════════════════════════════════════════

def detect_aruco_markers(frame):
    aruco_dict = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_4X4_50)
    parameters = cv2.aruco.DetectorParameters()
    detector = cv2.aruco.ArucoDetector(aruco_dict, parameters)
    corners, ids, _ = detector.detectMarkers(frame)
    return corners, ids

def is_inside_workspace(px, py, workspace_polygon):
    """Check if pixel (px, py) is inside the workspace polygon."""
    return cv2.pointPolygonTest(workspace_polygon, (float(px), float(py)), False) >= 0

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--webcam", action="store_true",
                        help="Force laptop webcam — use this to test YOLO without the robot connected")
    parser.add_argument("--camera", type=int, default=None,
                        help="Manually specify a camera index")
    parser.add_argument("--detect-people", action="store_true",
                        help="Also detect people in addition to books")
    args = parser.parse_args()

    # Build target classes based on flags
    target_classes = ["book", "bottle"]

    # ── Model ─────────────────────────────────────────────────────────────────
    # (load early so we can resolve class name → YOLO class ID)
    print(f"[INFO] Loading {MODEL_PATH} ...")
    model = YOLO(MODEL_PATH)
    print("[INFO] Model ready.")

    # Map target class names to YOLO numeric IDs so we can filter at inference
    yolo_class_ids = [
        cid for cid, name in model.names.items()
        if name in target_classes
    ]
    print(f"[INFO] Filtering for classes: {target_classes}  (YOLO IDs: {yolo_class_ids})")

    # ── Pick camera ───────────────────────────────────────────────────────────
    if args.camera is not None:
        cam_index  = args.camera
        robot_mode = not args.webcam

    elif args.webcam:
        cam_index  = 0
        robot_mode = False
        print("[CAM] Webcam mode forced — robot camera scan skipped.")

    else:
        robot_cam = find_robot_camera()
        if robot_cam is not None:
            cam_index  = robot_cam
            robot_mode = True
        else:
            cam_index  = 0
            robot_mode = False
            print("[CAM] Falling back to webcam at index 0.")

    cap = open_camera(cam_index, robot_mode)
    w   = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    h   = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

    # ── Load calibrations ─────────────────────────────────────────────────────
    cam_matrix, dist_coeffs, focal_px = load_camera_calibration()
    ws_polygon, ws_homography = load_workspace_calibration()

    # Software zoom level (change at runtime with + / - keys)
    zoom = ZOOM_DEFAULT

    mode_label = "ROBOT CAM" if robot_mode else "WEBCAM (test)"
    print(f"\n[INFO] Running — {mode_label} — press 'q' to quit.\n")

    try:
        while True:
            ret, frame = cap.read()
            if not ret:
                print("[WARN] Frame grab failed — retrying ...")
                time.sleep(0.05)
                continue

            # ── Software zoom (centre crop + upscale) ─────────────────────────
            frame = crop_zoom(frame, zoom)
            # ── Undistort if calibration available ───────────────────────
            if cam_matrix is not None:
                frame = cv2.undistort(frame, cam_matrix, dist_coeffs)
            # ── YOLO inference ────────────────────────────────────────────────
            results = model.predict(
                source=frame,
                imgsz=max(w, h),
                conf=CONFIDENCE_THRESH,
                classes=yolo_class_ids,
                verbose=False,
            )

            best_box  = None
            best_conf = 0.0
            best_class = None

            for result in results:
                for box in result.boxes:
                    class_name = model.names[int(box.cls)]
                    if class_name in target_classes:
                        conf = float(box.conf)
                        if conf > best_conf:
                            best_conf = conf
                            best_box  = box.xyxy[0].cpu().numpy()
                            best_class = class_name

            # ── Detection result ──────────────────────────────────────────────
            if best_box is not None:
                x1, y1, x2, y2  = best_box
                depth_m          = estimate_depth_m(x2 - x1, focal_px)
                cx_norm, cy_norm = bbox_centre_normalised(x1, y1, x2, y2, w, h)
                x = cx_norm
                y = cy_norm
                z = depth_m

                # Check workspace boundary using saved calibration
                obj_cx = int((x1 + x2) / 2)
                obj_cy = int((y1 + y2) / 2)
                if ws_polygon is not None:
                    inside = is_inside_workspace(obj_cx, obj_cy, ws_polygon)
                else:
                    inside = True   # no workspace calibration → accept all

                if inside:
                    print(f"[DETECT] {best_class.upper()} found  conf={best_conf:.2f}  "
                          f"coords=({x:+.2f}, {y:+.2f}, {z:.2f}m)")
                    send_to_arm(x, y, z)

            # ── Display ───────────────────────────────────────────────────────
            display = frame.copy()

            # Draw workspace boundary (cyan outline)
            if ws_polygon is not None:
                cv2.polylines(display, [ws_polygon], isClosed=True,
                              color=(255, 200, 0), thickness=2)

            if best_box is not None:
                box_color  = (0, 255, 0) if inside else (0, 0, 255)
                label_text = f"{best_class} {best_conf:.2f} | {depth_m:.2f}m"
                if not inside:
                    label_text += " [OUTSIDE]"

                cv2.rectangle(display,
                              (int(x1), int(y1)),
                              (int(x2), int(y2)),
                              box_color, 2)
                cv2.putText(display, label_text,
                            (int(x1), max(int(y1) - 8, 12)),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.5, box_color, 1)

            # Mode / zoom label top-left
            cv2.putText(display, f"{mode_label}  zoom {zoom:.2f}x", (6, 18),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.45,
                        (0, 200, 255) if robot_mode else (100, 100, 255), 1)

            cv2.imshow("Book Detection", display)
            key = cv2.waitKey(1) & 0xFF
            if key == ord("q"):
                break
            elif key in (ord("+"), ord("=")):   # '+' or '=' to zoom in
                zoom = min(zoom + ZOOM_STEP, ZOOM_MAX)
                print(f"[ZOOM] {zoom:.2f}x")
            elif key == ord("-"):                 # '-' to zoom out
                zoom = max(zoom - ZOOM_STEP, ZOOM_MIN)
                print(f"[ZOOM] {zoom:.2f}x")

    finally:
        cap.release()
        cv2.destroyAllWindows()
        print("[INFO] Done.")


if __name__ == "__main__":
    main()